mail.host=sandbox.smtp.mailtrap.io
mail.port=2525
mail.username=03d8cb94cdecad
mail.password=99802fbe89b4cf
app.mail=hello.thefurniturestore@gmail.com
app.name=thefurniturestore
#app.url=http://localhost:8080/thefurniturestore
#app.public.url=https://6089daf4b63b.ngrok-free.app/thefurniturestore
app.url=https://stipulate-chirping-material.ngrok-free.dev/thefurniturestore
app.public.url=https://stipulate-chirping-material.ngrok-free.dev/thefurniturestore

payhere.merchant.id=1236042
payhere.merchant.secret=MzE5MjA3ODY2MjMwNzExNjc4MjYxOTg4MTE1MTY1Mzg0OTk2MzU4OQ==
payhere.sandbox=true

