app.name=The Furniture Store
app.url=http://localhost:8080/thefurniturestore
app.public.url=https://stipulate-chirping-material.ngrok-free.dev/thefurniturestore
payhere.sandbox=true
hibernate.ddl.auto=update

payhere.merchant.id=1236042
payhere.merchant.secret=MzE5MjA3ODY2MjMwNzExNjc4MjYxOTg4MTE1MTY1Mzg0OTk2MzU4OQ==