mail.host=sandbox.smtp.mailtrap.io
mail.port=2525
mail.username=6414074c074806
mail.password=8724c9b38a516d
app.mail=info.thefurniturestore@gmail.com
app.name=thefurniturestore
app.url=http://localhost:9090/thefurniturestore
app.public.url=https://6089daf4b63b.ngrok-free.app